version: '3'
services:
  db:
    image: facerecog
    environment:
      POSTGRES_DB: imagedb
    volumes:
        # - ./database:/docker-entrypoint-initdb.d
        - ./database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 15672:15672
